Enemy
HIBIKI5201/Dungeon-Crafter pull request #34
Opened 2024-10-28 13:49 UTC by LengaTakamura

(仮)Generator

2024-10-28 13:59 UTC, HIBIKI5201 requested changes
レビュー通りに変更を行ってください

2024-10-28 13:59 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +
DCFrameWork.Enemy
のnamespaceを付けてください

2024-10-28 13:59 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            total += item;
配列の合計値を出すならLinqのSumを使うと楽です

2024-10-28 13:59 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        objectPool = new ObjectPool<GameObject>(() =>
ObjectPoolの定義は長くなるので、Startメソッドに収めると冗長になります
専用の関数を用意するとStartメソッドが簡潔になり全体の流れが見やすくなります

2024-10-28 13:59 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            var result = ChooseNum(items);
resultをintにすれば下記でintにキャストする手間が省けます

2024-10-29 13:28 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +
これは三つ全部にやる感じ？

2024-10-29 13:34 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            total += item;
済

2024-10-29 13:34 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        objectPool = new ObjectPool<GameObject>(() =>
済

2024-10-29 13:36 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            var result = ChooseNum(items);
これ結局 ChooseNum(items)がfloat返してるからcast不可欠かも

2024-10-29 13:38 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            var result = ChooseNum(items);
てかなんかenemyブランチコンパイルエラー出てるからとりあえずなんもせんとく

2024-10-29 14:10 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +            var result = ChooseNum(items);
プレイヤーブランチ領域の問題を修正

2024-10-30 08:38 UTC, merged