Enemy
HIBIKI5201/Dungeon-Crafter pull request #48
Opened 2024-11-01 15:56 UTC by LengaTakamura

2024-11-01 22:07 UTC, HIBIKI5201 requested changes
追加の要項として、Resources/Prefab/Enemyのフォルダに完成した敵のプレハブを追加してください

2024-11-02 07:22 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_S/NormalEnemyManager.cs
> +            Debug.Log("shinu");
消しました

2024-11-02 07:25 UTC, LengaTakamura commented
諸々修正したので確認お願いします

2024-11-02 08:05 UTC, HIBIKI5201 approved these changes
変更内容を確認しました

2024-11-02 08:05 UTC, merged