[Fix]generatorに機能が集中していた問題を解決　ヘルスバーの更新タイミングをアクション時に変更　スピード変更メソッドの作成
HIBIKI5201/Dungeon-Crafter pull request #59
Opened 2024-11-05 12:39 UTC by LengaTakamura

2024-11-05 14:53 UTC, HIBIKI5201 requested changes

2024-11-05 14:53 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +               manager.DeathAction = null;
ここで初期化しているのは何故ですか？

2024-11-05 14:53 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        public float _spawnInterval;
intervalやmaxNumは初期値を設定しておいた方が初歩的なエラーを回避できます
また_maxNumsは複数形ですが、これは単数のように思えます

2024-11-05 14:53 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _target = GameObject.Find("TargetPos").GetComponent<Transform>();
なぜGeneratorから参照しないのですか？
Findはリスクが非常に高いので避けるべきです

2024-11-05 14:53 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        private bool _isDead;
この変数は何に必要ですか？

2024-11-05 17:04 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _target = GameObject.Find("TargetPos").GetComponent<Transform>();
targetがserializedできないのでfindを使ってました
navmeshの初期化はgeneratorでおこなう方向で良いですか？

2024-11-05 17:05 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _target = GameObject.Find("TargetPos").GetComponent<Transform>();
初期化メソッドの引数にTransformを入れるのが良いでしょう

2024-11-05 17:08 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _target = GameObject.Find("TargetPos").GetComponent<Transform>();
了解です

2024-11-05 17:16 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        private bool _isDead;
エネミーの体力が０以下になってプールに返された後もaddDamageが呼び出されるのでそれを防ぐためにboolの変数を作りました

2024-11-05 17:23 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        public float _spawnInterval;
直しました

2024-11-05 17:24 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +               manager.DeathAction = null;
poolに戻された際にdeathActionが再度呼び出されていたので
deathActionがたまっていることが原因と考え初期化しました

2024-11-05 17:26 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        private bool _isDead;
それはTarret側に問題があるので、Issueを発行してこちら側からは何もしない方が健全だと思います
Turret側と共有した上でどちらで対応するべきか協議して下さい

2024-11-05 17:30 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +               manager.DeathAction = null;
なるほど、その場合、初期化する時ではなくDeathBehaviourで初期化した方が無駄な参照を持たずに綺麗になると思います

2024-11-05 17:30 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        private bool _isDead;
わかりました

2024-11-05 17:30 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +               manager.DeathAction = null;
了解です

2024-11-05 17:42 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +               manager.DeathAction = null;
修正しました　

2024-11-05 17:42 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _target = GameObject.Find("TargetPos").GetComponent<Transform>();
修正しました

2024-11-05 23:33 UTC, HIBIKI5201 requested changes

2024-11-05 23:33 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _deathAction = null;
DeathActionをnullにしてからInvokeすると実行されなくなりませんか？

2024-11-05 23:33 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        void Initialize(Vector3 transform);
変数名がtransformにも関わらず型はVector3座標である事は混乱が生じます

2024-11-05 23:33 UTC, HIBIKI5201 commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        public int _maxNum = 100 ;
numは単に「値」という意味なので、valueの方が適切だと思われます

2024-11-06 13:12 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        void Initialize(Vector3 transform);
posに修正しました

2024-11-06 13:14 UTC, LengaTakamura commented on Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs
> +        public int _maxNum = 100 ;
修正しました

2024-11-06 14:04 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        void Initialize(Vector3 transform);
transformPosという変数名にも関わらずTransformクラスではなくVector3である事は混乱が生じます
引数をTransformにするか、引数の名前をtargetPosなどに変更すると良いでしょう

2024-11-06 14:06 UTC, HIBIKI5201 commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _deathAction = null;
この件はどうなりましたか

2024-11-06 14:09 UTC, HIBIKI5201 requested changes
レビューしたので確認してください

2024-11-06 14:11 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +        void Initialize(Vector3 transform);
targetPosに統一しました

2024-11-06 14:12 UTC, LengaTakamura commented on Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> +            _deathAction = null;
忘れてました
順番逆で大丈夫そうですか？

2024-11-06 14:25 UTC, HIBIKI5201 approved these changes

2024-11-06 14:49 UTC, merged